// --------------------------------------------------------------------------------------------------------------------
// <copyright file="IReportingPeriodSerializer{TValue}.cs" company="OBeautifulCode">
//    Copyright (c) OBeautifulCode 2017. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.AccountingTime.Serialization source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.AccountingTime.Serialization
{
    using System;

    using MongoDB.Bson;
    using MongoDB.Bson.Serialization;
    using MongoDB.Bson.Serialization.Serializers;

    using static System.FormattableString;

    /// <inheritdoc />
#if !OBeautifulCodeAccountingTimeSerializationRecipesProject
    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.AccountingTime.Serialization", "See package version number")]
#endif
    internal class IReportingPeriodSerializer<TValue> : SerializerBase<TValue>
        where TValue : class, IReportingPeriod<UnitOfTime>
    {
        /// <inheritdoc />
        public override TValue Deserialize(BsonDeserializationContext context, BsonDeserializationArgs args)
        {


            var type = context.Reader.GetCurrentBsonType();
            switch (type)
            {
                case BsonType.Document:
                    var persistenceModel = ReportingPeriodPersistenceModel.Serializer.Deserialize(context);
                    var reportingPeriod = (persistenceModel.Start + "," + persistenceModel.End).DeserializeFromString<TValue>();
                    return reportingPeriod;
                case BsonType.Null:
                    context.Reader.ReadNull();
                    return default(TValue);
                default:
                    throw new NotSupportedException(Invariant($"Cannot convert a {type} to a {typeof(TValue).Name}."));
            }
        }

        /// <inheritdoc />
        public override void Serialize(BsonSerializationContext context, BsonSerializationArgs args, TValue value)
        {
            if (value == null)
            {
                context.Writer.WriteNull();
            }
            else
            {
                var persistenceModel = new ReportingPeriodPersistenceModel
                {
                    Start = value.Start.SerializeToSortableString(),
                    End = value.End.SerializeToSortableString()
                };

                ReportingPeriodPersistenceModel.Serializer.Serialize(context, persistenceModel);
            }
        }
    }
}
