// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UnitOfTimeConverter.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.AccountingTime.Serialization source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

#if OBeautifulCodeAccountingTimeSerializationRecipesProject
namespace OBeautifulCode.AccountingTime.Serialization
#else
namespace $rootnamespace$
#endif
{
    using System;

    using Newtonsoft.Json;

#if !OBeautifulCodeAccountingTimeSerializationRecipesProject
    using OBeautifulCode.AccountingTime;

    [System.Diagnostics.DebuggerStepThrough]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.AccountingTime.Serialization", "See package version number")]
#endif
    internal class ReportingPeriodConverter : JsonConverter
    {
        /// <inheritdoc />
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            var reportingPeriod = value as IReportingPeriod<UnitOfTime>;
            if (reportingPeriod != null)
            {
                var stringToWrite = reportingPeriod.SerializeToString();
                writer.WriteValue(stringToWrite);
            }
        }

        /// <inheritdoc />
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            object result = null;
            if (reader.Value != null)
            {
                result = reader.Value.ToString().DeserializeFromString(objectType);
            }

            return result;
        }

        /// <inheritdoc />
        public override bool CanConvert(Type objectType)
        {
            if (objectType.IsGenericType)
            {
                var genericType = objectType.MakeGenericType();
                var result = genericType == typeof(IReportingPeriod<>);
                return result;
            }

            return false;
        }
    }
}
