// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.85.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.AccountingTime.Test
{
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics.CodeAnalysis;

    using global::FakeItEasy;
    
    using global::OBeautifulCode.Assertion.Recipes;

    using global::Xunit;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.85.0")]
    public static partial class AccountingTimeDummyFactoryTest
    {
        [Fact]
        public static void AccountingTimeDummyFactory___Should_derive_from_DefaultAccountingTimeDummyFactory___When_reflecting()
        {
            // Arrange
            var dummyFactoryType = typeof(AccountingTimeDummyFactory);

            var defaultDummyFactoryType = typeof(DefaultAccountingTimeDummyFactory);

            // Act, Assert
            defaultDummyFactoryType.GetInterface(nameof(IDummyFactory)).AsTest().Must().NotBeNull();

            dummyFactoryType.BaseType.AsTest().Must().BeEqualTo(defaultDummyFactoryType);
        }
    }
}